let img = "http://localhost:8080/static/img/icon.png";
const testData={
	portrait:img
	,
	//MessageList组件展示的消息列表数据
	messageList:[
		{
			id:1,
			portrait:img,
			title:"微信团队",
			text:"[链接]登录操作通知",
			dateTime:"08:14",
			number:1
		},{
			id:2,
			portrait:img,
			title:"往后余生",
			text:"[图片]",
			dateTime:"08:29",
			number:0
		},{
			id:3,
			portrait:img,
			title:"龙锦苑东四",
			text:"东四-凯:想找个月嫂",
			dateTime:"08:14",
			number:12
		},{
			id:4,
			portrait:img,
			title:"Chat作者群",
			text:"[20条]我不叫大脸猫",
			dateTime:"08:14",
			number:89
		},{
			id:5,
			portrait:img,
			title:"犊子",
			text:"王金瑞:你看看",
			dateTime:"09/23",
			number:100
		},
	]
	,
	messages:[
		{
			id:1,
			from:1001,
			to:1002,
			messageId:"ABC",
			message:"应该难度不大吧？哦对了，有一个leaderboard需要用到动画animation来实现对比上一次答题本次答题的排位变化这个可做吗？应该难度不大吧？哦对了，有一个leaderboard需要用到动画animation来实现对比上一次答题本次答题的排位变化这个可做吗？"
		},
		{
			id:2,
			from:1002,
			to:1001,
			messageId:"ABC",
			message:"难度不大可以做。animation我用过，问题不大。"
		},
		{
			id:3,
			from:1001,
			to:1002,
			messageId:"ABC",
			message:"好，那我这边商议一下具体内容。主要现在我这边需要把学习内容敲定下来，我到时也发过来看一下。"
		},
		{
			id:4,
			from:1002,
			to:1001,
			messageId:"ABC",
			message:"屏幕取色软件是一些可以帮助用户抓取屏幕上任意颜色的工具，当在制作网页或者设置字体颜色的时候，喜欢屏幕上的某种颜色，因为不知道颜色的代码，不知如何获取，屏幕取色软件可以快速准确的获取到你想要的那种颜色，屏幕取色软件操作非常简单，无需学习任何操作方法，即可轻松掌握抓取要领，想抓什么颜色就抓什么颜色，非常适合网页设计者、程序编写者们使用，今天PC6小编就给大家搜集了多款Mac平台上的屏幕取色软件，希望能帮到大家！"
		},
		{
			id:5,
			from:1001,
			to:1002,
			messageId:"ABC",
			message:"这个没问题。"
		}
	]
}

export {
	testData
}